test:
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_username: <%= ENV['MAILER_USERNAME'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  mailer_authentication: <%= ENV['MAILER_AUTHENTICATION'] %>